repos:
  - repo: local
    hooks:
      - id: format
        name: Format code and docs
        entry: uv run task format
        language: system
        types: [python]
        pass_filenames: false

      - id: lint
        name: Lint code and type check
        entry: uv run task lint
        language: system
        types: [python]
        pass_filenames: false

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-merge-conflict
      - id: check-added-large-files