#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

if [ "$1" = "--fix" ]; then
  echo "==> Running lints with --fix"
  uv run ruff check --fix .
else
  echo "==> Running lints"
  uv run ruff check .
  uv run pyright
fi

echo "==> Making sure it imports"
uv run python -c 'import agentex'
