name: OpenGrep

on:
  pull_request: {}

concurrency:
  group: opengrep-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  opengrep:
    uses: scaleapi/required-actions/.github/workflows/opengrep-ci.yml@opengrep-4core-runner
    secrets: inherit
